name: Github Actions Demo
on:
  push:
    branches: 
      - main
    paths-ignore: 
      - '.github/**'
  pull_request:
    branches: 
      - main
  schedule:
    - cron: "15 6 * * SUN"
  workflow_dispatch:
  
jobs:
  build:
    name: "Build"
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3.3.0
      - run: echo "${{github.event_name}}"
      - run: echo "${{github.repository}}"
      - run: ls -l
