name: Workflow-1
on:  
  workflow_dispatch:
    inputs:
      Name:
        description: input the name
        required: true
        default: kgunnarsson
  schedule:
          - cron: '*/15 6 6 * *'  
jobs:  
  echo-step:
    environment: testing-2
    runs-on: ubuntu-latest
    steps:
      - run : |
          echo "hello  ${{inputs.Nam}}"
          
